### ISSUE TITLE
Write a simple tutorial for a developer user

### ISSUE THREAD

**Issue by rufuspollock** [pudo/nomenklatura#24]
- [ ] Explain in one/two sentence what this does for me
- [ ] Walk me through what i do to get started (do this as a screencast for bonus points)
- [ ] Link/feature on front page

**Comment by pudo** [comment]
Hi! I'm resetting this project to work off of other tooling I've worked on for the last few years. Check out the README for details. Closing all issues as they won't pertain to the new codebase.
