### ISSUE TITLE
Internal Server Error on Import

### ISSUE THREAD

**Issue by DavidRLowe** [pudo/nomenklatura#45]
I've not been able to upload my names. I've got a csv with 2 columns (UniqueID & Name) and ~110,000 rows. I've tried with scv, tab, and excel. Is it just too many entities?

**Comment by pudo** [comment]
Can you give me some detail: what site are you uploading to? The newest version at opennames.org was taken down, so I assume you mean the one at OKFNLabs?

**Comment by disneycorporation** [comment]
Hi, and thanks. I was trying to upload here
<http://nomenklatura.okfnlabs.org/>.

David

**Comment by shrouta** [comment]
I am having exactly the same problem, with an entity list of ~700 rows.  Was there ever a resolution to this?
