### ISSUE TITLE
nomenklatura installation

### ISSUE THREAD

**Issue by JBPressac** [pudo/nomenklatura#46]
Hello,
It seems that the hosted version of nomeklatura (http://nomenklatura.okfnlabs.org/) is not working any more. I also tried to upload a CSV file with 238 lines and two columns and everything I get is a 502 Bad Gateway error... Well, well.

So I tried to install nomenklatura on my computer: I downloaded the ZIP file https://github.com/pudo/nomenklatura/archive/master.zip, created a python vitual environement with miniconda and run the setup.py file (python setup.py install). But I don't really know what to do next to launch nomenklatura. Could you help ?

I also figure out if the files you provide on GitHub are for installing a replica of http://nomenklatura.okfnlabs.org/ ?

Thanks,

**Comment by pudo** [comment]
Hi @JBPressac! This repository has gone through a bunch of versions and is currently in a state that is extremely broken. If you wish to continue developing this, the version that is deployed on OKFNLabs is ``dca64bafab55a69a1324c3a99afc29f161c95cb8`` and there's an active branch with more modern functionality at https://github.com/robbi5/nomenklatura.

**Comment by JBPressac** [comment]
Thanks !
