### ISSUE TITLE
Match alias

### ISSUE THREAD

**Issue by johncordeiro** [pudo/nomenklatura#47]
This system is not matching alias for entities. I created an alias for "Rio de Janeiro" called "Rio", but it doesn't match when I call the following API: http://nomenklatura.uniceflabs.org/api/2/datasets/brazil-states/reconcile?query=rio

**Comment by pudo** [comment]
Are you running against the current ``master`` branch?

**Comment by pudo** [comment]
Hi! I'm resetting this project to work off of other tooling I've worked on for the last few years. Check out the README for details. Closing all issues as they won't pertain to the new codebase.
