### ISSUE TITLE
Re-introduce ``/lookup`` API call

### ISSUE THREAD

**Issue by pudo** [pudo/nomenklatura#48]
Find an entity; and if it doesn't exist create it

**Comment by steve-lynx** [comment]
It seems that the lookup method is not implemented  (http://nomenklatura.okfnlabs.org/P-IT_01/lookup?name=Barletta&api_key=...)  or temporarily disabled.

**Comment by pudo** [comment]
Hi! I'm resetting this project to work off of other tooling I've worked on for the last few years. Check out the README for details. Closing all issues as they won't pertain to the new codebase.
