### ISSUE TITLE
502 Bad Gateway error after uploading CSV file

### ISSUE THREAD

**Issue by Aubreymcfato** [pudo/nomenklatura#49]
I tried several time to create a dataset, uploading a csv or tsv, but it always gives me a 502. A friend of mine gets the same error.

**Comment by pudo** [comment]
Which instance are you referring to?

**Comment by Aubreymcfato** [comment]
Sorry, this one: http://nomenklatura.okfnlabs.org/

**Comment by steve-lynx** [comment]
Same for http://nomenklatura.okfnlabs.org/P-IT_01/upload/175

**Comment by pudo** [comment]
Unfortunately, it also looks like the server [is being shut down](https://discuss.okfn.org/t/announcing-shut-down-of-the-labs-server/2437). I would just beg everyone not to use this any more. Pretty please.

**Comment by pwalsh** [comment]
@steve-lynx @pudo is there another instance of Nomeklatura? We can keep hosting it, we are just shutting down that machine.

As for it being down right now, @danfowler can you please check the Nomenklatura running in the Labs server?

**Comment by Aubreymcfato** [comment]
Yes, thank you. I don't understand if there is another Nomenklatura online, or if the service is shut down for good.

**Comment by pudo** [comment]
For the moment, I don't think there's a general-purpose, free-for-all instance that I'd recommend using.
