### ISSUE TITLE
failing to create new entity

### ISSUE THREAD

**Issue by ParthaMoman** [pudo/nomenklatura#54]
Trying to post from rapidpro SMS platform to this. - i.e when a user reaches a certain point in a flow their response is added as a new entity to a specific dataset on nomenklatura (so we can then review) following: http://nomenklatura.uniceflabs.org/api/2/entities?name=@flow.settlement.text&dataset=somsettlementsbaidoa&api_key=

getting a 500 error in response - any ideas?

**Comment by pudo** [comment]
Hi! I'm resetting this project to work off of other tooling I've worked on for the last few years. Check out the README for details. Closing all issues as they won't pertain to the new codebase.
