### ISSUE TITLE
Issue with Importing CSV

### ISSUE THREAD

**Issue by schm1651** [pudo/nomenklatura#55]
I am trying to import a csv, I have it saved on my end as a csv(comma delimited) encoded as UTF-8.  I enter it in and hit import, I see it count up the "%" , but nothing happens in the end, and I can never access my files to begin processing. Any Help?

**Comment by pudo** [comment]
Hi! I'm resetting this project to work off of other tooling I've worked on for the last few years. Check out the README for details. Closing all issues as they won't pertain to the new codebase.
