### ISSUE TITLE
Delete a dataset

### ISSUE THREAD

**Issue by psychemedia** [pudo/nomenklatura#9]
It's likely that when trialling nomenklatura, new users (such as myself) will generate one or more test datasets to get a feel for the service and how it works.

It could be useful to allow users with an easy way of deleting their own datasets, and also freeing up the namespace that they used to inhabit so that it can be reused?

There is a danger that someone might delete a dataset that someone else is reusing, which could be mitigated by allowing users to clone other peoples' datasets? The datasets may then diverge of course, as each user updates their own copy.

**Comment by pudo** [comment]
Hi! I'm resetting this project to work off of other tooling I've worked on for the last few years. Check out the README for details. Closing all issues as they won't pertain to the new codebase.
